version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/.github/*"
    schedule:
      interval: "weekly"

  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"

# FIXME: Need other way to update OAS.
  # - package-ecosystem: "gitsubmodule"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
