version: 1
builder:
  configs:
  - documentation_targets:
    - GitHubRestAPISearch
    - GitHubRestAPIReactions
    - GitHubRestAPIMeta
    - GitHubRestAPIGit
    - GitHubRestAPIEmojis
    - GitHubRestAPIInteractions
    - GitHubRestAPIDependabot
    - GitHubRestAPIMarkdown
    - GitHubRestAPIChecks
    - GitHubRestAPIApps
    - GitHubRestAPIUsers
    - GitHubRestAPICopilot
    - GitHubRestAPIRepos
    - GitHubRestAPIRate_Limit
    - GitHubRestAPITeams
    - GitHubRestAPIPulls
    - GitHubRestAPISecurity_Advisories
    - GitHubRestAPIActions
    - GitHubRestAPIMigrations
    - GitHubRestAPIIssues
    - GitHubRestAPIGists
    - GitHubRestAPICodespaces
    - GitHubRestAPICodes_Of_Conduct
    - GitHubRestAPISecret_Scanning
    - GitHubRestAPICode_Scanning
    - GitHubRestAPIClassroom
    - GitHubRestAPIProjects
    - GitHubRestAPIOrgs
    - GitHubRestAPIDependency_Graph
    - GitHubRestAPILicenses
    - GitHubRestAPIPackages
    - GitHubRestAPIOidc
    - GitHubRestAPIActivity
    - GitHubRestAPIBilling
    - GitHubRestAPIGitignore
    - GitHubRestAPIDesktop
    - GitHubRestAPIMerge_Queue