version: 1
builder:
  configs:
  - documentation_targets:
    - GitHubRestAPIActions
    - GitHubRestAPIActivity
    - GitHubRestAPIAgentTasks
    - GitHubRestAPIAgents
    - GitHubRestAPIApps
    - GitHubRestAPIBilling
    - GitHubRestAPICampaigns
    - GitHubRestAPIChecks
    - GitHubRestAPIClassroom
    - GitHubRestAPICodeQuality
    - GitHubRestAPICodeScanning
    - GitHubRestAPICodeSecurity
    - GitHubRestAPICodesOfConduct
    - GitHubRestAPICodespaces
    - GitHubRestAPICopilot
    - GitHubRestAPICopilotSpaces
    - GitHubRestAPICredentials
    - GitHubRestAPIDependabot
    - GitHubRestAPIDependencyGraph
    - GitHubRestAPIDesktop
    - GitHubRestAPIEmojis
    - GitHubRestAPIEnterpriseTeamMemberships
    - GitHubRestAPIEnterpriseTeamOrganizations
    - GitHubRestAPIEnterpriseTeams
    - GitHubRestAPIGists
    - GitHubRestAPIGit
    - GitHubRestAPIGitignore
    - GitHubRestAPIHostedCompute
    - GitHubRestAPIInteractions
    - GitHubRestAPIIssues
    - GitHubRestAPILicenses
    - GitHubRestAPIMarkdown
    - GitHubRestAPIMergeQueue
    - GitHubRestAPIMeta
    - GitHubRestAPIMigrations
    - GitHubRestAPIOidc
    - GitHubRestAPIOrgs
    - GitHubRestAPIPackages
    - GitHubRestAPIPrivateRegistries
    - GitHubRestAPIProjects
    - GitHubRestAPIProjectsClassic
    - GitHubRestAPIPulls
    - GitHubRestAPIRateLimit
    - GitHubRestAPIReactions
    - GitHubRestAPIRepos
    - GitHubRestAPISearch
    - GitHubRestAPISecretScanning
    - GitHubRestAPISecurityAdvisories
    - GitHubRestAPITeams
    - GitHubRestAPIUsers
