version: 1
builder:
  configs:
  - documentation_targets:
    - GitHubRestAPIActions
    - GitHubRestAPIActivity
    - GitHubRestAPIApps
    - GitHubRestAPIBilling
    - GitHubRestAPICampaigns
    - GitHubRestAPIChecks
    - GitHubRestAPIClassroom
    - GitHubRestAPICode_Scanning
    - GitHubRestAPICode_Security
    - GitHubRestAPICodes_Of_Conduct
    - GitHubRestAPICodespaces
    - GitHubRestAPICopilot
    - GitHubRestAPIDependabot
    - GitHubRestAPIDependency_Graph
    - GitHubRestAPIDesktop
    - GitHubRestAPIEmojis
    - GitHubRestAPIEnterprise_Teams
    - GitHubRestAPIGists
    - GitHubRestAPIGit
    - GitHubRestAPIGitignore
    - GitHubRestAPIHosted_Compute
    - GitHubRestAPIInteractions
    - GitHubRestAPIIssues
    - GitHubRestAPILicenses
    - GitHubRestAPIMarkdown
    - GitHubRestAPIMerge_Queue
    - GitHubRestAPIMeta
    - GitHubRestAPIMigrations
    - GitHubRestAPIOidc
    - GitHubRestAPIOrgs
    - GitHubRestAPIPackages
    - GitHubRestAPIPrivate_Registries
    - GitHubRestAPIProjects
    - GitHubRestAPIPulls
    - GitHubRestAPIRate_Limit
    - GitHubRestAPIReactions
    - GitHubRestAPIRepos
    - GitHubRestAPISearch
    - GitHubRestAPISecret_Scanning
    - GitHubRestAPISecurity_Advisories
    - GitHubRestAPITeams
    - GitHubRestAPIUsers
