name: Setup

description: Setup for swift, cache, etc.

inputs:
  os:
    required: true

runs:
  using: 'composite'
  steps:

    - uses: jdx/mise-action@v4
      env:
        MISE_DATA_DIR: ${{ runner.temp }}/${{ github.action }}/mise
     
    - name: "Xcode Cache"
      if: contains(inputs.os, 'macos')
      uses: irgaly/xcode-cache@v1
      with:
        key: ${{ runner.os }}-xcode-cache-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-xcode-cache-

    - name: "Swift Package Manager Cache"
      uses: actions/cache@v5
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
  
    - name: "Compiling Cache"
      uses: actions/cache@v5
      with:
        path: ~/Library/Caches/org.swift.swiftpm/
        key: ${{ runner.os }}-swift-build-${{ github.ref_name }}
        restore-keys: |
          ${{ runner.os }}-swift-build-
  
  # Hint: Use Composite Actions 
  # - https://stackoverflow.com/a/75735736/9801139
  # - https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-public-action-in-a-subdirectory
  # - https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
  # - https://dev.to/n3wt0n/composite-actions-vs-reusable-workflows-what-is-the-difference-github-actions-11kd
