//
//  PackageBuilder.swift
//  github-rest-api-swift-openapi
//
//  Created by zwc on 2024/1/6.
//

import Foundation

struct ErrorMessage: LocalizedError {
    var message: String
    var errorDescription: String? { message }
    init(message: String, line: Int = #line) {
        self.message = "\(line): \(message)"
    }
}

/// Refreshes the generated `sourceFolders` list in Package.swift.
///
/// The manifest itself owns all naming and target-assembly logic; this script
/// only rewrites the data between the GENERATED markers from the direct
/// subdirectories of Sources/.
struct PackageBuilder {

    static let beginMarker = "// BEGIN GENERATED by `make Package.swift`"
    static let endMarker = "// END GENERATED"

    let manifestPath: String

    private func sourceFolders() throws -> [String] {
        let sourcesURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
            .appendingPathComponent("Sources")
        return try FileManager.default
            .contentsOfDirectory(
                at: sourcesURL,
                includingPropertiesForKeys: [.isDirectoryKey],
                options: .skipsHiddenFiles
            )
            .filter { (try? $0.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) == true }
            .map(\.lastPathComponent)
            .sorted()
    }

    func write() throws {
        let manifestURL = URL(fileURLWithPath: manifestPath)
        let manifest = try String(contentsOf: manifestURL, encoding: .utf8)
        guard let beginRange = manifest.range(of: Self.beginMarker),
              let endRange = manifest.range(of: Self.endMarker),
              beginRange.upperBound <= endRange.lowerBound else {
            throw ErrorMessage(message: "GENERATED markers not found in \(manifestPath).")
        }
        let literal = "\nlet sourceFolders = [\n"
            + (try sourceFolders().map { "    \"\($0)\",\n" }.joined())
            + "]\n"
        let updated = manifest.replacingCharacters(
            in: beginRange.upperBound..<endRange.lowerBound,
            with: literal
        )
        guard let data = updated.data(using: .utf8) else {
            throw ErrorMessage(message: "Variable data not found.")
        }
        try data.write(to: manifestURL)
    }

}

if let argPath = CommandLine.arguments.dropFirst().first {
    try PackageBuilder(manifestPath: String(argPath)).write()
} else {
    throw ErrorMessage(message: "Manifest path argument not found.")
}
