name: CI

on: 
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  Test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
        swift: ["5.9"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/workflows/actions/setup
        with:
          swift: ${{ matrix.swift }}
          os: ${{ matrix.os }}
      - run: swift build
      - run: swift test
