name: CI

on: 
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  Test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
        swift: ["5.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/workflows/actions/setup
        with:
          swift: ${{ matrix.swift }}
          os: ${{ matrix.os }}
      - run: swift build
      - run: swift test

  # Package.swift uses GITHUB_JOB to add docc dependency
  # FIXME: Not expected docs.
  # BuildDocC:
  #   strategy:
  #     matrix:
  #       os:
  #         - ubuntu-latest
  #         # - macos-latest
  #       swift: ["5.9"]
  #   runs-on: ${{ matrix.os }}
  #   env:
  #     GITHUB_PAGES: "true"
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         submodules: true
  #     - uses: ./.github/workflows/actions/setup
  #       with:
  #         swift: ${{ matrix.swift }}
  #         os: ${{ matrix.os }}

  #     - run: make .build/docs
  #     - uses: actions/upload-pages-artifact@v3
  #       with:
  #         path: .build/docs

  # DeployDocC:
  #   needs: BuildDocC
  #   permissions:
  #     pages: write
  #     id-token: write
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}/documentation/githubrestapiswiftopenapi
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v4
  #       https://wei18.github.io/github-rest-api-swift-openapi/documentation/githubrestapidesktop/

