name: Dependabot Commit

on:
  pull_request:
    paths:
      - 'Submodule/**'

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  
  generate-sources:
    if: github.actor == 'dependabot[bot]'
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest #Fix: The macos-latest workflow label currently uses the macOS 12 runner image.
          # - macos-13

    runs-on: ${{ matrix.os }}
    timeout-minutes: 100
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          ref: ${{ github.head_ref }}

      - uses: ./.github/composites/setup
        with:
          os: ${{ matrix.os }}

      - uses: ./.github/composites/git-config

      - name: "Commit new sources"
        run: |
          make install
          git push
          
      - name: "Update pr metadata"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge --auto --merge "$PR_URL"
          gh pr review --approve "$PR_URL"
          
