name: Dependabot update commit

on:
  pull_request:
    paths:
      - 'Submodule/**'

permissions:
  contents: write
  pull-requests: write
  
jobs:
  Sync:
    if: github.actor == 'dependabot[bot]'
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest #Fix: The macos-latest workflow label currently uses the macOS 12 runner image.
          # - macos-13
        swift: ["5.9"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/workflows/actions/setup
        with:
          swift: ${{ matrix.swift }}
          os: ${{ matrix.os }}
      - name: "Sync code base"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh pr checkout ${{ github.event.pull_request.number }}
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          make install
          git push
          gh pr merge --auto --merge "$PR_URL"
          gh pr review --approve "$PR_URL"
          
