name: Dependabot update commit

on:
  pull_request:
    paths:
      - 'Submodule/**' 

permissions:
  pull-requests: write
  
jobs:
  Sync:
    if: github.actor == 'dependabot[bot]'
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
        swift: ["5.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/workflows/actions/setup
        with:
          swift: ${{ matrix.swift }}
          os: ${{ matrix.os }}
      - run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: touch Submodule
      - run: make install
      - run: git push
      - env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --merge "$PR_URL"
          
