name: Publish Doc

on:
  release:
    types:
      - published
      - edited
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/Doc.yml'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # https://github.com/apple/swift-docc/issues/255#issuecomment-1125685372
  # https://github.com/sersoft-gmbh/oss-common-actions/blob/main/.github/workflows/swift-generate-and-publish-docs.yml
  generate-and-publish-docs:
    uses: sersoft-gmbh/oss-common-actions/.github/workflows/swift-generate-and-publish-docs.yml@main
    with:
      os: ubuntu
      swift-version: '5.9'
      organisation: ${{ github.repository_owner }}
      repository: ${{ github.event.repository.name }}
      pages-branch: gh-pages
